name: Build and publish binary wheels onto PyPi (testing)
on:
  workflow_dispatch:

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        target:
          - name: Windows (x64)
            os: windows-latest
            archs: AMD64
            msvc: 1
          - name: Ubuntu (x64)
            os: ubuntu-latest
            archs: x86_64
          - name: macOS (x64)
            os: macos-13
            archs: x86_64

    name: Wheels for ${{ matrix.target.name }} 
    runs-on: ${{ matrix.target.os }}

    steps:
      - uses: actions/checkout@v4
      - uses: actions/checkout@v4
        with:
          repository: 'bbopt/nomad'
          ref: 'v.4.4.0'
          path: './nomad'
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Build binary wheels
        uses: pypa/cibuildwheel@v3.1.4
        env:
          CIBW_ARCHS: >-
            ${{ matrix.target.archs }}
          CIBW_BEFORE_ALL: >-
            cd ./nomad &&
            cmake -DTEST_OPENMP=OFF -DBUILD_EXAMPLES=OFF -DBUILD_INTERFACE_PYTHON=ON -S . -B build &&
            cmake --build build --config Release --clean-first --target nomadStatic --parallel 2 &&
            cd ..
          CIBW_ENVIRONMENT: >-
            NOMAD_PATH=./nomad
            NOMAD_MSVC=${{ matrix.target.msvc }}
          CIBW_TEST_REQUIRES: >-
            pytest 
            numpy
          CIBW_TEST_COMMAND: >-
            pytest -v {project}/tests
          CIBW_PROJECT_REQUIRES_PYTHON: >-
            >=3.11
          CIBW_BUILD_FRONTEND: >-
            build
          CIBW_BUILD_VERBOITY: >-
            3
        with:
          output-dir: wheelhouse

      - name: Collect wheels for processing
        uses: actions/upload-artifact@v4
        with:
          path: wheelhouse/*.whl

  # We use pypa/gh-action-pypi-publish to upload the binary wheels onto PyPi.

  publish:
    name: Publish to PyPi (testing)
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Collect wheels for publication
        uses: actions/download-artifact@v4
        with:
          name: artifact
          path: wheelhouse

      - name: Publish wheels to PyPi (testing)
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          repository-url: https://test.pypi.org/legacy/
          password: ${{ secrets.PYPI_TESTING_API_TOKEN }}
          packages_dir: wheelhouse
          skip_existing: true
